export { default as IcBackSvg } from '@app-assets/svgs/IcBackSvg';
export { default as IcCmtSvg } from '@app-assets/svgs/IcCmtSvg';
export { default as IcGenre } from '@app-assets/svgs/IcGenre';
export { default as IcGroupSvg } from '@app-assets/svgs/IcGroupSvg';
export { default as IcHashTagSvg } from '@app-assets/svgs/IcHashTagSvg';
export { default as IcPenSvg } from '@app-assets/svgs/IcPenSvg';
export { default as IcPlusSvg } from '@app-assets/svgs/IcPlusSvg';
export { default as IcSettingSvg } from '@app-assets/svgs/IcSettingSvg';
export { default as IcUploadSvg } from '@app-assets/svgs/IcUploadSvg';
